#ifndef AMITY_SPS_INC_RESOLVER_SHADER_TYPES
#define AMITY_SPS_INC_RESOLVER_SHADER_TYPES
#include <HLSLSupport.cginc>
#include <UnityInstancing.cginc>

UNITY_INSTANCING_BUFFER_START(AmitySpsResolverProps)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_Legacy)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_Enabled)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagInclude1)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagInclude1Self)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagInclude1Others)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagInclude2)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagInclude2Self)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagInclude2Others)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagInclude3)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagInclude3Self)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagInclude3Others)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagInclude4)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagInclude4Self)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagInclude4Others)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagExclude1)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagExclude1Self)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagExclude1Others)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagExclude2)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagExclude2Self)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagExclude2Others)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagExclude3)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagExclude3Self)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagExclude3Others)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagExclude4)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagExclude4Self)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_TagExclude4Others)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_BakedLength)
    UNITY_DEFINE_INSTANCED_PROP(float, _SPS_BakedRadius)
    UNITY_DEFINE_INSTANCED_PROP(float4, _SPS_MetadataColor)
    UNITY_DEFINE_INSTANCED_PROP(float4, _SPS_BakedRadiusSamples0)
    UNITY_DEFINE_INSTANCED_PROP(float4, _SPS_BakedRadiusSamples1)
    UNITY_DEFINE_INSTANCED_PROP(float4, _SPS_BakedRadiusSamples2)
    UNITY_DEFINE_INSTANCED_PROP(float4, _SPS_BakedRadiusSamples3)
    UNITY_DEFINE_INSTANCED_PROP(float4, _SPS_BakedRadiusSamples4)
    UNITY_DEFINE_INSTANCED_PROP(float4, _SPS_BakedRadiusSamples5)
    UNITY_DEFINE_INSTANCED_PROP(float4, _SPS_BakedRadiusSamples6)
    UNITY_DEFINE_INSTANCED_PROP(float4, _SPS_BakedRadiusSamples7)
UNITY_INSTANCING_BUFFER_END(AmitySpsResolverProps)

#define _SPS_Legacy UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_Legacy)
#define _SPS_Enabled UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_Enabled)
#define _SPS_TagInclude1 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagInclude1)
#define _SPS_TagInclude1Self UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagInclude1Self)
#define _SPS_TagInclude1Others UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagInclude1Others)
#define _SPS_TagInclude2 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagInclude2)
#define _SPS_TagInclude2Self UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagInclude2Self)
#define _SPS_TagInclude2Others UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagInclude2Others)
#define _SPS_TagInclude3 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagInclude3)
#define _SPS_TagInclude3Self UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagInclude3Self)
#define _SPS_TagInclude3Others UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagInclude3Others)
#define _SPS_TagInclude4 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagInclude4)
#define _SPS_TagInclude4Self UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagInclude4Self)
#define _SPS_TagInclude4Others UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagInclude4Others)
#define _SPS_TagExclude1 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagExclude1)
#define _SPS_TagExclude1Self UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagExclude1Self)
#define _SPS_TagExclude1Others UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagExclude1Others)
#define _SPS_TagExclude2 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagExclude2)
#define _SPS_TagExclude2Self UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagExclude2Self)
#define _SPS_TagExclude2Others UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagExclude2Others)
#define _SPS_TagExclude3 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagExclude3)
#define _SPS_TagExclude3Self UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagExclude3Self)
#define _SPS_TagExclude3Others UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagExclude3Others)
#define _SPS_TagExclude4 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagExclude4)
#define _SPS_TagExclude4Self UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagExclude4Self)
#define _SPS_TagExclude4Others UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_TagExclude4Others)
#define _SPS_BakedLength UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_BakedLength)
#define _SPS_BakedRadius UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_BakedRadius)
#define _SPS_MetadataColor UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_MetadataColor)
#define _SPS_BakedRadiusSamples0 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_BakedRadiusSamples0)
#define _SPS_BakedRadiusSamples1 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_BakedRadiusSamples1)
#define _SPS_BakedRadiusSamples2 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_BakedRadiusSamples2)
#define _SPS_BakedRadiusSamples3 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_BakedRadiusSamples3)
#define _SPS_BakedRadiusSamples4 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_BakedRadiusSamples4)
#define _SPS_BakedRadiusSamples5 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_BakedRadiusSamples5)
#define _SPS_BakedRadiusSamples6 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_BakedRadiusSamples6)
#define _SPS_BakedRadiusSamples7 UNITY_ACCESS_INSTANCED_PROP(AmitySpsResolverProps, _SPS_BakedRadiusSamples7)

#endif
