#ifndef AMITY_SPS_INC_TYPES
#define AMITY_SPS_INC_TYPES

#include "sps_flags.cginc"

#define AMITY_SPS_SOCKET_FLAG_HOLE 1u
#define AMITY_SPS_SOCKET_FLAG_DOUBLE_SIDED 2u
#define AMITY_SPS_SOCKET_FLAG_PORTAL 4u
#define AMITY_SPS_SOCKET_FLAG_RADIUS_OFFSET 8u

// Non-prefixed aliases for VRCFury compatibility
#define SPS_SOCKET_FLAG_HOLE AMITY_SPS_SOCKET_FLAG_HOLE
#define SPS_SOCKET_FLAG_DOUBLE_SIDED AMITY_SPS_SOCKET_FLAG_DOUBLE_SIDED
#define SPS_SOCKET_FLAG_PORTAL AMITY_SPS_SOCKET_FLAG_PORTAL
#define SPS_SOCKET_FLAG_RADIUS_OFFSET AMITY_SPS_SOCKET_FLAG_RADIUS_OFFSET

#endif
